### ISSUE TITLE
Create database to hold users, transactions, financial goals, and debts

### ISSUE THREAD

**Issue by BezDailey** [BezDailey/Budgeting-App-Backend#1]
## Description
The purpose of this ticket to implement a database that holds `users`, `transactions`, `financial goals`, `budget`, and `debts`.

### Requirements
* The `users` table should at least hold `userID`, `username`, `password`, and `email`.
* The  `transactions` table should at least hold `transactionID`, `transactionName`, and `transactionCategory`
* The `financial goals` table should at least hold `goalID`, `goalName`, `goalAmount`, and `goalAmountSaved`
* The `budget` table should at least hold `budgetID`, `budgetCategories` (will hold an array), `budgetExpectedAmount`(will hold an array), and `budgetActualAmount`(will hold an array)
  * The array indexies will map to a budget category.

### Todo
* [ ] Pick database system valid options `sqlite3` (works well with python), `mysql`, `mongoDB`, etc..
* [ ] Create `users` table.
* [ ] Create `transactions` table.
* [ ] Create `financial goals` table.
* [ ] Create `budget` table.
